package dao;

import java.util.List;
import model.Member;
import model.MemberExample;
import org.apache.ibatis.annotations.Param;

public interface MemberMapper {
   
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	int countByExample(MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	int deleteByExample(MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	int deleteByPrimaryKey(String uid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	int insert(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	int insertSelective(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */List<Member> selectByExample(MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	Member selectByPrimaryKey(String uid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */int updateByExampleSelective(@Param("record") Member record,@Param("example") MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */int updateByExample(@Param("record") Member record,@Param("example") MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	int updateByPrimaryKeySelective(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	int updateByPrimaryKey(Member record);

	String  getmembername(String uid);
   
}