package dao;

import java.util.List;
import model.Member;
import model.MemberExample;
import org.apache.ibatis.annotations.Param;

public interface MemberMapper {
   
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	int countByExample(MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	int deleteByExample(MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	int deleteByPrimaryKey(String uid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	int insert(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	int insertSelective(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	List<Member> selectByExample(MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	Member selectByPrimaryKey(String uid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	int updateByExampleSelective(@Param("record") Member record, @Param("example") MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	int updateByExample(@Param("record") Member record, @Param("example") MemberExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	int updateByPrimaryKeySelective(Member record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	int updateByPrimaryKey(Member record);

	String  getmembername(String uid);
   
}