package dao;

import java.util.List;
import model.Note;
import model.NoteExample;
import org.apache.ibatis.annotations.Param;

public interface NoteMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table note
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	int countByExample(NoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table note
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	int deleteByExample(NoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table note
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	int deleteByPrimaryKey(String uid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table note
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	int insert(Note record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table note
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	int insertSelective(Note record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table note
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */List<Note> selectByExample(NoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table note
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	Note selectByPrimaryKey(String uid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table note
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */int updateByExampleSelective(@Param("record") Note record,@Param("example") NoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table note
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */int updateByExample(@Param("record") Note record,@Param("example") NoteExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table note
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	int updateByPrimaryKeySelective(Note record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table note
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	int updateByPrimaryKey(Note record);
}