package model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class MemberExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public MemberExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andUidIsNull() {
			addCriterion("UID is null");
			return (Criteria) this;
		}

		public Criteria andUidIsNotNull() {
			addCriterion("UID is not null");
			return (Criteria) this;
		}

		public Criteria andUidEqualTo(String value) {
			addCriterion("UID =", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotEqualTo(String value) {
			addCriterion("UID <>", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidGreaterThan(String value) {
			addCriterion("UID >", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidGreaterThanOrEqualTo(String value) {
			addCriterion("UID >=", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLessThan(String value) {
			addCriterion("UID <", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLessThanOrEqualTo(String value) {
			addCriterion("UID <=", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidLike(String value) {
			addCriterion("UID like", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotLike(String value) {
			addCriterion("UID not like", value, "uid");
			return (Criteria) this;
		}

		public Criteria andUidIn(List<String> values) {
			addCriterion("UID in", values, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotIn(List<String> values) {
			addCriterion("UID not in", values, "uid");
			return (Criteria) this;
		}

		public Criteria andUidBetween(String value1, String value2) {
			addCriterion("UID between", value1, value2, "uid");
			return (Criteria) this;
		}

		public Criteria andUidNotBetween(String value1, String value2) {
			addCriterion("UID not between", value1, value2, "uid");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("username is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("username is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("username =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("username <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("username >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("username >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("username <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("username <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("username like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("username not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("username in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("username not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("username between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("username not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andTruenameIsNull() {
			addCriterion("TrueName is null");
			return (Criteria) this;
		}

		public Criteria andTruenameIsNotNull() {
			addCriterion("TrueName is not null");
			return (Criteria) this;
		}

		public Criteria andTruenameEqualTo(String value) {
			addCriterion("TrueName =", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameNotEqualTo(String value) {
			addCriterion("TrueName <>", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameGreaterThan(String value) {
			addCriterion("TrueName >", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameGreaterThanOrEqualTo(String value) {
			addCriterion("TrueName >=", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameLessThan(String value) {
			addCriterion("TrueName <", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameLessThanOrEqualTo(String value) {
			addCriterion("TrueName <=", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameLike(String value) {
			addCriterion("TrueName like", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameNotLike(String value) {
			addCriterion("TrueName not like", value, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameIn(List<String> values) {
			addCriterion("TrueName in", values, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameNotIn(List<String> values) {
			addCriterion("TrueName not in", values, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameBetween(String value1, String value2) {
			addCriterion("TrueName between", value1, value2, "truename");
			return (Criteria) this;
		}

		public Criteria andTruenameNotBetween(String value1, String value2) {
			addCriterion("TrueName not between", value1, value2, "truename");
			return (Criteria) this;
		}

		public Criteria andSexIsNull() {
			addCriterion("Sex is null");
			return (Criteria) this;
		}

		public Criteria andSexIsNotNull() {
			addCriterion("Sex is not null");
			return (Criteria) this;
		}

		public Criteria andSexEqualTo(Integer value) {
			addCriterion("Sex =", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotEqualTo(Integer value) {
			addCriterion("Sex <>", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThan(Integer value) {
			addCriterion("Sex >", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexGreaterThanOrEqualTo(Integer value) {
			addCriterion("Sex >=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThan(Integer value) {
			addCriterion("Sex <", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexLessThanOrEqualTo(Integer value) {
			addCriterion("Sex <=", value, "sex");
			return (Criteria) this;
		}

		public Criteria andSexIn(List<Integer> values) {
			addCriterion("Sex in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotIn(List<Integer> values) {
			addCriterion("Sex not in", values, "sex");
			return (Criteria) this;
		}

		public Criteria andSexBetween(Integer value1, Integer value2) {
			addCriterion("Sex between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andSexNotBetween(Integer value1, Integer value2) {
			addCriterion("Sex not between", value1, value2, "sex");
			return (Criteria) this;
		}

		public Criteria andSignmessageIsNull() {
			addCriterion("SignMessage is null");
			return (Criteria) this;
		}

		public Criteria andSignmessageIsNotNull() {
			addCriterion("SignMessage is not null");
			return (Criteria) this;
		}

		public Criteria andSignmessageEqualTo(String value) {
			addCriterion("SignMessage =", value, "signmessage");
			return (Criteria) this;
		}

		public Criteria andSignmessageNotEqualTo(String value) {
			addCriterion("SignMessage <>", value, "signmessage");
			return (Criteria) this;
		}

		public Criteria andSignmessageGreaterThan(String value) {
			addCriterion("SignMessage >", value, "signmessage");
			return (Criteria) this;
		}

		public Criteria andSignmessageGreaterThanOrEqualTo(String value) {
			addCriterion("SignMessage >=", value, "signmessage");
			return (Criteria) this;
		}

		public Criteria andSignmessageLessThan(String value) {
			addCriterion("SignMessage <", value, "signmessage");
			return (Criteria) this;
		}

		public Criteria andSignmessageLessThanOrEqualTo(String value) {
			addCriterion("SignMessage <=", value, "signmessage");
			return (Criteria) this;
		}

		public Criteria andSignmessageLike(String value) {
			addCriterion("SignMessage like", value, "signmessage");
			return (Criteria) this;
		}

		public Criteria andSignmessageNotLike(String value) {
			addCriterion("SignMessage not like", value, "signmessage");
			return (Criteria) this;
		}

		public Criteria andSignmessageIn(List<String> values) {
			addCriterion("SignMessage in", values, "signmessage");
			return (Criteria) this;
		}

		public Criteria andSignmessageNotIn(List<String> values) {
			addCriterion("SignMessage not in", values, "signmessage");
			return (Criteria) this;
		}

		public Criteria andSignmessageBetween(String value1, String value2) {
			addCriterion("SignMessage between", value1, value2, "signmessage");
			return (Criteria) this;
		}

		public Criteria andSignmessageNotBetween(String value1, String value2) {
			addCriterion("SignMessage not between", value1, value2, "signmessage");
			return (Criteria) this;
		}

		public Criteria andHeadimageIsNull() {
			addCriterion("HeadImage is null");
			return (Criteria) this;
		}

		public Criteria andHeadimageIsNotNull() {
			addCriterion("HeadImage is not null");
			return (Criteria) this;
		}

		public Criteria andHeadimageEqualTo(String value) {
			addCriterion("HeadImage =", value, "headimage");
			return (Criteria) this;
		}

		public Criteria andHeadimageNotEqualTo(String value) {
			addCriterion("HeadImage <>", value, "headimage");
			return (Criteria) this;
		}

		public Criteria andHeadimageGreaterThan(String value) {
			addCriterion("HeadImage >", value, "headimage");
			return (Criteria) this;
		}

		public Criteria andHeadimageGreaterThanOrEqualTo(String value) {
			addCriterion("HeadImage >=", value, "headimage");
			return (Criteria) this;
		}

		public Criteria andHeadimageLessThan(String value) {
			addCriterion("HeadImage <", value, "headimage");
			return (Criteria) this;
		}

		public Criteria andHeadimageLessThanOrEqualTo(String value) {
			addCriterion("HeadImage <=", value, "headimage");
			return (Criteria) this;
		}

		public Criteria andHeadimageLike(String value) {
			addCriterion("HeadImage like", value, "headimage");
			return (Criteria) this;
		}

		public Criteria andHeadimageNotLike(String value) {
			addCriterion("HeadImage not like", value, "headimage");
			return (Criteria) this;
		}

		public Criteria andHeadimageIn(List<String> values) {
			addCriterion("HeadImage in", values, "headimage");
			return (Criteria) this;
		}

		public Criteria andHeadimageNotIn(List<String> values) {
			addCriterion("HeadImage not in", values, "headimage");
			return (Criteria) this;
		}

		public Criteria andHeadimageBetween(String value1, String value2) {
			addCriterion("HeadImage between", value1, value2, "headimage");
			return (Criteria) this;
		}

		public Criteria andHeadimageNotBetween(String value1, String value2) {
			addCriterion("HeadImage not between", value1, value2, "headimage");
			return (Criteria) this;
		}

		public Criteria andEmailIsNull() {
			addCriterion("Email is null");
			return (Criteria) this;
		}

		public Criteria andEmailIsNotNull() {
			addCriterion("Email is not null");
			return (Criteria) this;
		}

		public Criteria andEmailEqualTo(String value) {
			addCriterion("Email =", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotEqualTo(String value) {
			addCriterion("Email <>", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThan(String value) {
			addCriterion("Email >", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailGreaterThanOrEqualTo(String value) {
			addCriterion("Email >=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThan(String value) {
			addCriterion("Email <", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLessThanOrEqualTo(String value) {
			addCriterion("Email <=", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailLike(String value) {
			addCriterion("Email like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotLike(String value) {
			addCriterion("Email not like", value, "email");
			return (Criteria) this;
		}

		public Criteria andEmailIn(List<String> values) {
			addCriterion("Email in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotIn(List<String> values) {
			addCriterion("Email not in", values, "email");
			return (Criteria) this;
		}

		public Criteria andEmailBetween(String value1, String value2) {
			addCriterion("Email between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andEmailNotBetween(String value1, String value2) {
			addCriterion("Email not between", value1, value2, "email");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andLoginfailIsNull() {
			addCriterion("loginFail is null");
			return (Criteria) this;
		}

		public Criteria andLoginfailIsNotNull() {
			addCriterion("loginFail is not null");
			return (Criteria) this;
		}

		public Criteria andLoginfailEqualTo(Integer value) {
			addCriterion("loginFail =", value, "loginfail");
			return (Criteria) this;
		}

		public Criteria andLoginfailNotEqualTo(Integer value) {
			addCriterion("loginFail <>", value, "loginfail");
			return (Criteria) this;
		}

		public Criteria andLoginfailGreaterThan(Integer value) {
			addCriterion("loginFail >", value, "loginfail");
			return (Criteria) this;
		}

		public Criteria andLoginfailGreaterThanOrEqualTo(Integer value) {
			addCriterion("loginFail >=", value, "loginfail");
			return (Criteria) this;
		}

		public Criteria andLoginfailLessThan(Integer value) {
			addCriterion("loginFail <", value, "loginfail");
			return (Criteria) this;
		}

		public Criteria andLoginfailLessThanOrEqualTo(Integer value) {
			addCriterion("loginFail <=", value, "loginfail");
			return (Criteria) this;
		}

		public Criteria andLoginfailIn(List<Integer> values) {
			addCriterion("loginFail in", values, "loginfail");
			return (Criteria) this;
		}

		public Criteria andLoginfailNotIn(List<Integer> values) {
			addCriterion("loginFail not in", values, "loginfail");
			return (Criteria) this;
		}

		public Criteria andLoginfailBetween(Integer value1, Integer value2) {
			addCriterion("loginFail between", value1, value2, "loginfail");
			return (Criteria) this;
		}

		public Criteria andLoginfailNotBetween(Integer value1, Integer value2) {
			addCriterion("loginFail not between", value1, value2, "loginfail");
			return (Criteria) this;
		}

		public Criteria andPhonenumIsNull() {
			addCriterion("PhoneNum is null");
			return (Criteria) this;
		}

		public Criteria andPhonenumIsNotNull() {
			addCriterion("PhoneNum is not null");
			return (Criteria) this;
		}

		public Criteria andPhonenumEqualTo(String value) {
			addCriterion("PhoneNum =", value, "phonenum");
			return (Criteria) this;
		}

		public Criteria andPhonenumNotEqualTo(String value) {
			addCriterion("PhoneNum <>", value, "phonenum");
			return (Criteria) this;
		}

		public Criteria andPhonenumGreaterThan(String value) {
			addCriterion("PhoneNum >", value, "phonenum");
			return (Criteria) this;
		}

		public Criteria andPhonenumGreaterThanOrEqualTo(String value) {
			addCriterion("PhoneNum >=", value, "phonenum");
			return (Criteria) this;
		}

		public Criteria andPhonenumLessThan(String value) {
			addCriterion("PhoneNum <", value, "phonenum");
			return (Criteria) this;
		}

		public Criteria andPhonenumLessThanOrEqualTo(String value) {
			addCriterion("PhoneNum <=", value, "phonenum");
			return (Criteria) this;
		}

		public Criteria andPhonenumLike(String value) {
			addCriterion("PhoneNum like", value, "phonenum");
			return (Criteria) this;
		}

		public Criteria andPhonenumNotLike(String value) {
			addCriterion("PhoneNum not like", value, "phonenum");
			return (Criteria) this;
		}

		public Criteria andPhonenumIn(List<String> values) {
			addCriterion("PhoneNum in", values, "phonenum");
			return (Criteria) this;
		}

		public Criteria andPhonenumNotIn(List<String> values) {
			addCriterion("PhoneNum not in", values, "phonenum");
			return (Criteria) this;
		}

		public Criteria andPhonenumBetween(String value1, String value2) {
			addCriterion("PhoneNum between", value1, value2, "phonenum");
			return (Criteria) this;
		}

		public Criteria andPhonenumNotBetween(String value1, String value2) {
			addCriterion("PhoneNum not between", value1, value2, "phonenum");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNull() {
			addCriterion("password is null");
			return (Criteria) this;
		}

		public Criteria andPasswordIsNotNull() {
			addCriterion("password is not null");
			return (Criteria) this;
		}

		public Criteria andPasswordEqualTo(String value) {
			addCriterion("password =", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotEqualTo(String value) {
			addCriterion("password <>", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThan(String value) {
			addCriterion("password >", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordGreaterThanOrEqualTo(String value) {
			addCriterion("password >=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThan(String value) {
			addCriterion("password <", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLessThanOrEqualTo(String value) {
			addCriterion("password <=", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordLike(String value) {
			addCriterion("password like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotLike(String value) {
			addCriterion("password not like", value, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordIn(List<String> values) {
			addCriterion("password in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotIn(List<String> values) {
			addCriterion("password not in", values, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordBetween(String value1, String value2) {
			addCriterion("password between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andPasswordNotBetween(String value1, String value2) {
			addCriterion("password not between", value1, value2, "password");
			return (Criteria) this;
		}

		public Criteria andRoletypeIsNull() {
			addCriterion("RoleType is null");
			return (Criteria) this;
		}

		public Criteria andRoletypeIsNotNull() {
			addCriterion("RoleType is not null");
			return (Criteria) this;
		}

		public Criteria andRoletypeEqualTo(Integer value) {
			addCriterion("RoleType =", value, "roletype");
			return (Criteria) this;
		}

		public Criteria andRoletypeNotEqualTo(Integer value) {
			addCriterion("RoleType <>", value, "roletype");
			return (Criteria) this;
		}

		public Criteria andRoletypeGreaterThan(Integer value) {
			addCriterion("RoleType >", value, "roletype");
			return (Criteria) this;
		}

		public Criteria andRoletypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("RoleType >=", value, "roletype");
			return (Criteria) this;
		}

		public Criteria andRoletypeLessThan(Integer value) {
			addCriterion("RoleType <", value, "roletype");
			return (Criteria) this;
		}

		public Criteria andRoletypeLessThanOrEqualTo(Integer value) {
			addCriterion("RoleType <=", value, "roletype");
			return (Criteria) this;
		}

		public Criteria andRoletypeIn(List<Integer> values) {
			addCriterion("RoleType in", values, "roletype");
			return (Criteria) this;
		}

		public Criteria andRoletypeNotIn(List<Integer> values) {
			addCriterion("RoleType not in", values, "roletype");
			return (Criteria) this;
		}

		public Criteria andRoletypeBetween(Integer value1, Integer value2) {
			addCriterion("RoleType between", value1, value2, "roletype");
			return (Criteria) this;
		}

		public Criteria andRoletypeNotBetween(Integer value1, Integer value2) {
			addCriterion("RoleType not between", value1, value2, "roletype");
			return (Criteria) this;
		}

		public Criteria andResourceIsNull() {
			addCriterion("Resource is null");
			return (Criteria) this;
		}

		public Criteria andResourceIsNotNull() {
			addCriterion("Resource is not null");
			return (Criteria) this;
		}

		public Criteria andResourceEqualTo(String value) {
			addCriterion("Resource =", value, "resource");
			return (Criteria) this;
		}

		public Criteria andResourceNotEqualTo(String value) {
			addCriterion("Resource <>", value, "resource");
			return (Criteria) this;
		}

		public Criteria andResourceGreaterThan(String value) {
			addCriterion("Resource >", value, "resource");
			return (Criteria) this;
		}

		public Criteria andResourceGreaterThanOrEqualTo(String value) {
			addCriterion("Resource >=", value, "resource");
			return (Criteria) this;
		}

		public Criteria andResourceLessThan(String value) {
			addCriterion("Resource <", value, "resource");
			return (Criteria) this;
		}

		public Criteria andResourceLessThanOrEqualTo(String value) {
			addCriterion("Resource <=", value, "resource");
			return (Criteria) this;
		}

		public Criteria andResourceLike(String value) {
			addCriterion("Resource like", value, "resource");
			return (Criteria) this;
		}

		public Criteria andResourceNotLike(String value) {
			addCriterion("Resource not like", value, "resource");
			return (Criteria) this;
		}

		public Criteria andResourceIn(List<String> values) {
			addCriterion("Resource in", values, "resource");
			return (Criteria) this;
		}

		public Criteria andResourceNotIn(List<String> values) {
			addCriterion("Resource not in", values, "resource");
			return (Criteria) this;
		}

		public Criteria andResourceBetween(String value1, String value2) {
			addCriterion("Resource between", value1, value2, "resource");
			return (Criteria) this;
		}

		public Criteria andResourceNotBetween(String value1, String value2) {
			addCriterion("Resource not between", value1, value2, "resource");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNull() {
			addCriterion("AddTime is null");
			return (Criteria) this;
		}

		public Criteria andAddtimeIsNotNull() {
			addCriterion("AddTime is not null");
			return (Criteria) this;
		}

		public Criteria andAddtimeEqualTo(Date value) {
			addCriterion("AddTime =", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotEqualTo(Date value) {
			addCriterion("AddTime <>", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThan(Date value) {
			addCriterion("AddTime >", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeGreaterThanOrEqualTo(Date value) {
			addCriterion("AddTime >=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThan(Date value) {
			addCriterion("AddTime <", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeLessThanOrEqualTo(Date value) {
			addCriterion("AddTime <=", value, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeIn(List<Date> values) {
			addCriterion("AddTime in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotIn(List<Date> values) {
			addCriterion("AddTime not in", values, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeBetween(Date value1, Date value2) {
			addCriterion("AddTime between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andAddtimeNotBetween(Date value1, Date value2) {
			addCriterion("AddTime not between", value1, value2, "addtime");
			return (Criteria) this;
		}

		public Criteria andAdduserIsNull() {
			addCriterion("AddUser is null");
			return (Criteria) this;
		}

		public Criteria andAdduserIsNotNull() {
			addCriterion("AddUser is not null");
			return (Criteria) this;
		}

		public Criteria andAdduserEqualTo(String value) {
			addCriterion("AddUser =", value, "adduser");
			return (Criteria) this;
		}

		public Criteria andAdduserNotEqualTo(String value) {
			addCriterion("AddUser <>", value, "adduser");
			return (Criteria) this;
		}

		public Criteria andAdduserGreaterThan(String value) {
			addCriterion("AddUser >", value, "adduser");
			return (Criteria) this;
		}

		public Criteria andAdduserGreaterThanOrEqualTo(String value) {
			addCriterion("AddUser >=", value, "adduser");
			return (Criteria) this;
		}

		public Criteria andAdduserLessThan(String value) {
			addCriterion("AddUser <", value, "adduser");
			return (Criteria) this;
		}

		public Criteria andAdduserLessThanOrEqualTo(String value) {
			addCriterion("AddUser <=", value, "adduser");
			return (Criteria) this;
		}

		public Criteria andAdduserLike(String value) {
			addCriterion("AddUser like", value, "adduser");
			return (Criteria) this;
		}

		public Criteria andAdduserNotLike(String value) {
			addCriterion("AddUser not like", value, "adduser");
			return (Criteria) this;
		}

		public Criteria andAdduserIn(List<String> values) {
			addCriterion("AddUser in", values, "adduser");
			return (Criteria) this;
		}

		public Criteria andAdduserNotIn(List<String> values) {
			addCriterion("AddUser not in", values, "adduser");
			return (Criteria) this;
		}

		public Criteria andAdduserBetween(String value1, String value2) {
			addCriterion("AddUser between", value1, value2, "adduser");
			return (Criteria) this;
		}

		public Criteria andAdduserNotBetween(String value1, String value2) {
			addCriterion("AddUser not between", value1, value2, "adduser");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNull() {
			addCriterion("UpdateTime is null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIsNotNull() {
			addCriterion("UpdateTime is not null");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeEqualTo(Date value) {
			addCriterion("UpdateTime =", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotEqualTo(Date value) {
			addCriterion("UpdateTime <>", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThan(Date value) {
			addCriterion("UpdateTime >", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
			addCriterion("UpdateTime >=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThan(Date value) {
			addCriterion("UpdateTime <", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
			addCriterion("UpdateTime <=", value, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeIn(List<Date> values) {
			addCriterion("UpdateTime in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotIn(List<Date> values) {
			addCriterion("UpdateTime not in", values, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeBetween(Date value1, Date value2) {
			addCriterion("UpdateTime between", value1, value2, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
			addCriterion("UpdateTime not between", value1, value2, "updatetime");
			return (Criteria) this;
		}

		public Criteria andUpdateuserIsNull() {
			addCriterion("UpdateUser is null");
			return (Criteria) this;
		}

		public Criteria andUpdateuserIsNotNull() {
			addCriterion("UpdateUser is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateuserEqualTo(String value) {
			addCriterion("UpdateUser =", value, "updateuser");
			return (Criteria) this;
		}

		public Criteria andUpdateuserNotEqualTo(String value) {
			addCriterion("UpdateUser <>", value, "updateuser");
			return (Criteria) this;
		}

		public Criteria andUpdateuserGreaterThan(String value) {
			addCriterion("UpdateUser >", value, "updateuser");
			return (Criteria) this;
		}

		public Criteria andUpdateuserGreaterThanOrEqualTo(String value) {
			addCriterion("UpdateUser >=", value, "updateuser");
			return (Criteria) this;
		}

		public Criteria andUpdateuserLessThan(String value) {
			addCriterion("UpdateUser <", value, "updateuser");
			return (Criteria) this;
		}

		public Criteria andUpdateuserLessThanOrEqualTo(String value) {
			addCriterion("UpdateUser <=", value, "updateuser");
			return (Criteria) this;
		}

		public Criteria andUpdateuserLike(String value) {
			addCriterion("UpdateUser like", value, "updateuser");
			return (Criteria) this;
		}

		public Criteria andUpdateuserNotLike(String value) {
			addCriterion("UpdateUser not like", value, "updateuser");
			return (Criteria) this;
		}

		public Criteria andUpdateuserIn(List<String> values) {
			addCriterion("UpdateUser in", values, "updateuser");
			return (Criteria) this;
		}

		public Criteria andUpdateuserNotIn(List<String> values) {
			addCriterion("UpdateUser not in", values, "updateuser");
			return (Criteria) this;
		}

		public Criteria andUpdateuserBetween(String value1, String value2) {
			addCriterion("UpdateUser between", value1, value2, "updateuser");
			return (Criteria) this;
		}

		public Criteria andUpdateuserNotBetween(String value1, String value2) {
			addCriterion("UpdateUser not between", value1, value2, "updateuser");
			return (Criteria) this;
		}

		public Criteria andMemoIsNull() {
			addCriterion("Memo is null");
			return (Criteria) this;
		}

		public Criteria andMemoIsNotNull() {
			addCriterion("Memo is not null");
			return (Criteria) this;
		}

		public Criteria andMemoEqualTo(String value) {
			addCriterion("Memo =", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotEqualTo(String value) {
			addCriterion("Memo <>", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoGreaterThan(String value) {
			addCriterion("Memo >", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoGreaterThanOrEqualTo(String value) {
			addCriterion("Memo >=", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoLessThan(String value) {
			addCriterion("Memo <", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoLessThanOrEqualTo(String value) {
			addCriterion("Memo <=", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoLike(String value) {
			addCriterion("Memo like", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotLike(String value) {
			addCriterion("Memo not like", value, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoIn(List<String> values) {
			addCriterion("Memo in", values, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotIn(List<String> values) {
			addCriterion("Memo not in", values, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoBetween(String value1, String value2) {
			addCriterion("Memo between", value1, value2, "memo");
			return (Criteria) this;
		}

		public Criteria andMemoNotBetween(String value1, String value2) {
			addCriterion("Memo not between", value1, value2, "memo");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table member
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table member
     *
     * @mbggenerated do_not_delete_during_merge Sat Aug 29 13:00:32 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}