package model;

import java.util.Date;

public class Member {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.UID
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	private String uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.username
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.TrueName
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	private String truename;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.Sex
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.SignMessage
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	private String signmessage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.HeadImage
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	private String headimage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.Email
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.status
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.loginFail
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	private Integer loginfail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.PhoneNum
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	private String phonenum;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.password
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.RoleType
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	private Integer roletype;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.Resource
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	private String resource;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.AddTime
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	private Date addtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.AddUser
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	private String adduser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.UpdateTime
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	private Date updatetime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.UpdateUser
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	private String updateuser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column member.Memo
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	private String memo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.UID
	 * @return  the value of member.UID
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.UID
	 * @param uid  the value for member.UID
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.username
	 * @return  the value of member.username
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.username
	 * @param username  the value for member.username
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.TrueName
	 * @return  the value of member.TrueName
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public String getTruename() {
		return truename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.TrueName
	 * @param truename  the value for member.TrueName
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public void setTruename(String truename) {
		this.truename = truename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.Sex
	 * @return  the value of member.Sex
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.Sex
	 * @param sex  the value for member.Sex
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.SignMessage
	 * @return  the value of member.SignMessage
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public String getSignmessage() {
		return signmessage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.SignMessage
	 * @param signmessage  the value for member.SignMessage
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public void setSignmessage(String signmessage) {
		this.signmessage = signmessage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.HeadImage
	 * @return  the value of member.HeadImage
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public String getHeadimage() {
		return headimage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.HeadImage
	 * @param headimage  the value for member.HeadImage
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public void setHeadimage(String headimage) {
		this.headimage = headimage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.Email
	 * @return  the value of member.Email
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.Email
	 * @param email  the value for member.Email
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.status
	 * @return  the value of member.status
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.status
	 * @param status  the value for member.status
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.loginFail
	 * @return  the value of member.loginFail
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public Integer getLoginfail() {
		return loginfail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.loginFail
	 * @param loginfail  the value for member.loginFail
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public void setLoginfail(Integer loginfail) {
		this.loginfail = loginfail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.PhoneNum
	 * @return  the value of member.PhoneNum
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public String getPhonenum() {
		return phonenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.PhoneNum
	 * @param phonenum  the value for member.PhoneNum
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public void setPhonenum(String phonenum) {
		this.phonenum = phonenum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.password
	 * @return  the value of member.password
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.password
	 * @param password  the value for member.password
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.RoleType
	 * @return  the value of member.RoleType
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public Integer getRoletype() {
		return roletype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.RoleType
	 * @param roletype  the value for member.RoleType
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public void setRoletype(Integer roletype) {
		this.roletype = roletype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.Resource
	 * @return  the value of member.Resource
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public String getResource() {
		return resource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.Resource
	 * @param resource  the value for member.Resource
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public void setResource(String resource) {
		this.resource = resource;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.AddTime
	 * @return  the value of member.AddTime
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public Date getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.AddTime
	 * @param addtime  the value for member.AddTime
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.AddUser
	 * @return  the value of member.AddUser
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public String getAdduser() {
		return adduser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.AddUser
	 * @param adduser  the value for member.AddUser
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public void setAdduser(String adduser) {
		this.adduser = adduser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.UpdateTime
	 * @return  the value of member.UpdateTime
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public Date getUpdatetime() {
		return updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.UpdateTime
	 * @param updatetime  the value for member.UpdateTime
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public void setUpdatetime(Date updatetime) {
		this.updatetime = updatetime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.UpdateUser
	 * @return  the value of member.UpdateUser
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public String getUpdateuser() {
		return updateuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.UpdateUser
	 * @param updateuser  the value for member.UpdateUser
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public void setUpdateuser(String updateuser) {
		this.updateuser = updateuser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column member.Memo
	 * @return  the value of member.Memo
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column member.Memo
	 * @param memo  the value for member.Memo
	 * @mbggenerated  Tue Feb 02 20:58:41 CST 2016
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}
}