package model;

import java.util.Date;

public class Note {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column note.UID
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	private String uid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column note.Content
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column note.Memo
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	private String memo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column note.Addtime
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	private Date addtime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column note.UID
	 * @return  the value of note.UID
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	public String getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column note.UID
	 * @param uid  the value for note.UID
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	public void setUid(String uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column note.Content
	 * @return  the value of note.Content
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column note.Content
	 * @param content  the value for note.Content
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column note.Memo
	 * @return  the value of note.Memo
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	public String getMemo() {
		return memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column note.Memo
	 * @param memo  the value for note.Memo
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	public void setMemo(String memo) {
		this.memo = memo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column note.Addtime
	 * @return  the value of note.Addtime
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	public Date getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column note.Addtime
	 * @param addtime  the value for note.Addtime
	 * @mbggenerated  Wed Nov 04 15:44:56 CST 2015
	 */
	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}
}